# Generated by Django 5.1.2 on 2024-10-14 10:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='место выполнения привычки')),
                ('time', models.TimeField(default=datetime.time(10, 29, 43, 313088), verbose_name='время выполнения привычки')),
                ('action', models.CharField(max_length=255, verbose_name='действие для привычки')),
                ('nice_habit', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('is_published', models.BooleanField(default=False, verbose_name='признак публичной привычки')),
                ('period', models.CharField(choices=[('daily', 'ежедневно'), ('weakly', 'еженедельно')], default='daily', max_length=150, verbose_name='период выполнения')),
                ('duration', models.TimeField(default=datetime.timedelta(seconds=120), verbose_name='время на выполнение')),
                ('award', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания привычки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
