# Generated by Django 5.1.2 on 2024-10-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_published',
            field=models.BooleanField(verbose_name='признак публичной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='nice_habit',
            field=models.BooleanField(verbose_name='признак приятной привычки'),
        ),
    ]
