# Generated by Django 5.1.2 on 2024-10-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_is_published_alter_habit_nice_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'еженедельно')], default='daily', max_length=150, verbose_name='период выполнения'),
        ),
    ]
